# This workflow will build a .NET project

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test ./test/Cdcn.Enterprise.Library.Tests/Cdcn.Enterprise.Library.Tests.csproj --configuration Release --no-build --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkg
    
    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for file in ./nupkg/*.nupkg; do
          dotnet nuget push "$file" --source "https://nuget.pkg.github.com/mycodecaine/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        done
